blank_issues_enabled: false
contact_links:
  - name: â“ General Questions
    url: https://github.com/OopsApps/discussions
    about: Please ask general questions in Discussions instead of creating issues.
